CREATE TABLE `email_jobs` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `toEmail` VARCHAR(191) NOT NULL,
  `subject` VARCHAR(191) NOT NULL,
  `htmlBody` LONGTEXT NOT NULL,
  `category` VARCHAR(191) NOT NULL,
  `mode` VARCHAR(191) NOT NULL DEFAULT 'IMMEDIATE',
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `priority` INTEGER NOT NULL DEFAULT 50,
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `maxAttempts` INTEGER NOT NULL DEFAULT 5,
  `nextAttemptAt` DATETIME(3) NULL,
  `lastAttemptAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `lockedAt` DATETIME(3) NULL,
  `lastError` TEXT NULL,
  `providerMessageId` VARCHAR(191) NULL,
  `dedupeKey` VARCHAR(191) NULL,
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `email_jobs_dedupeKey_key`(`dedupeKey`),
  INDEX `email_jobs_status_nextAttemptAt_idx`(`status`, `nextAttemptAt`),
  INDEX `email_jobs_category_idx`(`category`),
  INDEX `email_jobs_mode_idx`(`mode`),
  INDEX `email_jobs_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
